"""
Twilio Telephony Integration - LLM-Driven (No Fallbacks)
All responses generated by Gemini AI, no hardcoded responses
"""

import os
from flask import Flask, request, Response
from twilio.twiml.voice_response import VoiceResponse, Gather
from twilio.rest import Client
from dotenv import load_dotenv

from session_manager import session_manager
from auth_handler import auth_handler
from llm_handler import llm_handler
from data_store import get_order_details, create_refund_request
from guardrails_handler import GuardrailsHandler

# Load environment
load_dotenv()

# Initialize Flask app for webhooks
app = Flask(__name__)

# Initialize Twilio client
account_sid = os.getenv('TWILIO_ACCOUNT_SID')
auth_token = os.getenv('TWILIO_AUTH_TOKEN')
twilio_client = Client(account_sid, auth_token)


class TwilioVoiceAgent:
    """LLM-driven voice agent for handling calls with Gemini AI and Guardrails"""
    
    def __init__(self):
        self.active_sessions = {}  
        self.conversation_context = {}  
        self.order_context = {}  
        self.guardrails = GuardrailsHandler(llm_client=None) 
    
    def handle_incoming_call(self, call_sid):
        """Handle new incoming call"""
        # Create session
        session_id = session_manager.create_session()
        self.active_sessions[call_sid] = session_id
        self.conversation_context[session_id] = []
        
        # Greeting
        
        greeting = "Hello, customer support. How can I help you today?"
        
        # Store in conversation context
        self.conversation_context[session_id].append({
            'role': 'assistant',
            'content': greeting
        })
        
        # Add to session history
        session_manager.add_message(session_id, "agent", greeting)
        
        # Return greeting
        response = VoiceResponse()
        response.say(
            greeting,
            voice='Polly.Joanna',
            language='en-US'
        )
        
        
        gather = Gather(
            input='speech',
            action='/process_speech',
            method='POST',
            speech_timeout='auto',
            language='en-US',
            timeout=3  
        )
        response.append(gather)
        
        return str(response)
    
    def process_user_speech(self, call_sid, speech_result):
        """Process what user said - fully LLM-driven"""
        session_id = self.active_sessions.get(call_sid)
        if not session_id:
            return self._error_response("Session not found")
        
        # Validate input with guardrails
        is_valid, processed_input, rejection_reason = self.guardrails.validate_input(
            speech_result,
            self.conversation_context.get(session_id, [])
        )
        
        if not is_valid:
            # Input failed validation - return rejection message
            rejection_message = self.guardrails.get_rejection_message(rejection_reason)
            print(f"[Twilio] Input validation failed: {rejection_reason}")
            print(f"[Twilio] Returning rejection message to user")
            
            # Add rejection to conversation history
            session_manager.add_message(session_id, "user", speech_result)
            session_manager.add_message(session_id, "agent", rejection_message)
            
            # Create Twilio response
            response = VoiceResponse()
            response.say(rejection_message, voice='Polly.Joanna', language='en-US')
            
            # Gather next input
            gather = Gather(
                input='speech',
                action='/process_speech',
                method='POST',
                speech_timeout='auto',
                language='en-US',
                timeout=3
            )
            response.append(gather)
            
            return str(response)
        
        # Add user input to conversation context
        self.conversation_context[session_id].append({
            'role': 'user',
            'content': processed_input
        })
        
        # Add to session history
        session_manager.add_message(session_id, "user", processed_input)
        
        # Detect intent with conversation completion check
        intent_result = llm_handler.detect_intent(
            speech_result,
            self.conversation_context[session_id]
        )
        
        # Check if conversation is naturally complete
        if intent_result.get('conversation_complete', False):
            print(f"[Twilio] Conversation completion detected")
            return self._end_call(session_id, speech_result)
        
        # Check if explicit goodbye (fallback)
        if intent_result.get('intent') == 'goodbye':
            return self._end_call(session_id, speech_result)
        
        # Generate AI response
        agent_response = self._generate_llm_response(session_id, speech_result)
        
        # Add agent response to context
        self.conversation_context[session_id].append({
            'role': 'assistant',
            'content': agent_response
        })
        
        # Add to session history
        session_manager.add_message(session_id, "agent", agent_response)
        
        # Create Twilio response
        response = VoiceResponse()
        response.say(agent_response, voice='Polly.Joanna', language='en-US')
        
        # Gather next input with reduced timeout for speed
        gather = Gather(
            input='speech',
            action='/process_speech',
            method='POST',
            speech_timeout='auto',
            language='en-US',
            timeout=3  
        )
        response.append(gather)
        
        return str(response)
    
    def _generate_llm_response(self, session_id, user_input):
        """Generate response using LLM with full context"""
        
        # Check if in authentication flow
        if auth_handler.is_pending_auth(session_id):
            return self._handle_authentication(session_id, user_input)
        
        # Get session data
        session = session_manager.get_session(session_id)
        is_authenticated = session.get('authenticated', False)
        order_id = session.get('order_id')
        
        # Get order data if authenticated
        order_data = None
        if is_authenticated and order_id:
            if session_id not in self.order_context:
                self.order_context[session_id] = get_order_details(order_id)
            order_data = self.order_context[session_id]
        
        # Build comprehensive context for LLM
        context_prompt = self._build_context_prompt(
            session_id,
            user_input,
            is_authenticated,
            order_data
        )
        
        # Check if needs authentication
        needs_auth = self._check_needs_authentication(user_input, is_authenticated, session_id)
        
        if needs_auth and not is_authenticated:
            # Start authentication using LLM to explain
            return auth_handler.start_authentication(session_id)
        
        # Handle special actions (refund, etc.)
        action_result = self._handle_actions(session_id, user_input, order_data)
        if action_result:
            # Let LLM generate natural response about the action
            action_prompt = f"""The user said: "{user_input}"
            
Action completed: {action_result}

Generate a natural, conversational response that:
1. Confirms what was done
2. Provides the relevant details
3. Asks if they need anything else

Keep it friendly and concise (2-3 sentences)."""
            
            return llm_handler.generate_response(
                action_prompt,
                {"conversation_history": self.conversation_context[session_id][-5:]},
                order_data=order_data
            )
        
        # Generate natural response using LLM
        # LLM will handle scope restrictions internally
        response = llm_handler.generate_response(
            context_prompt,
            {
                "conversation_history": self.conversation_context[session_id],
                "authenticated": is_authenticated,
                "order_id": order_id
            },
            order_data=order_data
        )
        
        return response
    
    def _build_context_prompt(self, session_id, user_input, is_authenticated, order_data):
        """Build comprehensive prompt with all context"""
        
        # Get recent conversation
        recent_context = self.conversation_context[session_id][-5:] if session_id in self.conversation_context else []
        context_str = "\n".join([f"{msg['role']}: {msg['content']}" for msg in recent_context])
        
        prompt = f"""You are a professional customer support agent on a phone call.

Recent conversation:
{context_str}

Customer just said: "{user_input}"
"""
        
        if is_authenticated and order_data:
            prompt += f"""

Customer is authenticated. Current order details:
- Order ID: {order_data['order_id']}
- Product: {order_data['product']}
- Status: {order_data['status']}
- Delivery Date: {order_data['delivery_date']}
- Amount: ₹{order_data['amount']}

Use this information to provide specific, helpful answers.
"""
        
        prompt += """

Generate a natural, conversational response that:
1. Directly addresses what the customer said
2. Uses information from the context (don't repeat what was already said)
3. Provides specific details when available
4. Is warm and professional
5. Keeps responses concise (2-3 sentences max)
6. Asks follow-up questions when appropriate

Response:"""
        
        return prompt
    
    def _check_needs_authentication(self, user_input, is_authenticated, session_id):
        """Check if query needs authentication using LLM intent detection"""
        if is_authenticated:
            return False
        
        # Use LLM detect_intent with conversation context
        intent_result = llm_handler.detect_intent(
            user_input,
            self.conversation_context.get(session_id, [])
        )
        
        # Check if intent requires authentication
        return intent_result.get('requires_authentication', False)
    
    def _handle_authentication(self, session_id, user_input):
        """Handle authentication flow"""
        order_id, result = auth_handler.process_auth_input(session_id, user_input)
        
        if result == "verified":
            # Authentication successful
            session_manager.authenticate_session(session_id, order_id)
            
            # Get order data
            order_data = get_order_details(order_id)
            self.order_context[session_id] = order_data
            
            # Generate natural confirmation using LLM
            auth_prompt = f"""The customer just successfully authenticated for their order.

Order details:
- Order ID: {order_data['order_id']}
- Product: {order_data['product']}
- Status: {order_data['status']}

Generate a warm confirmation message that:
1. Thanks them for verifying
2. Mentions what order they're calling about
3. Asks how you can help with this order

Keep it natural and concise (2-3 sentences)."""
            
            return llm_handler.generate_response(
                auth_prompt,
                {},
                order_data=order_data
            )
        else:
            # Return the auth prompt or error from auth_handler
            return result
    
    def _handle_actions(self, session_id, user_input, order_data):
        """Handle actions like refunds, returns, etc."""
        
        # Check if user wants a refund
        if any(word in user_input.lower() for word in ['refund', 'return', 'money back']):
            if not order_data:
                return None  # Let LLM handle the "need auth" message
            
            # Extract reason using LLM
            reason_prompt = f"""User said: "{user_input}"

Extract the reason for the refund request in 2-5 words.
Examples: "damaged product", "wrong item", "late delivery", "changed mind"

Reason:"""
            
            reason = llm_handler.generate_response(reason_prompt, {}, None)
            reason = reason.strip().strip('"\'')
            
            # Create refund
            result = create_refund_request(order_data['order_id'], reason)
            
            if result["success"]:
                return f"Refund initiated. Refund ID: {result['refund_id']}. Order: {order_data['order_id']}. Product: {order_data['product']}."
            else:
                return "Refund processing failed. Technical issue occurred."
        
        return None
    
    def _is_goodbye(self, text):
        """Simple check if user is ending call"""
        goodbye_words = ['bye', 'goodbye', 'thank you bye', 'that\'s all', 'end call']
        text_lower = text.lower()
        return any(word in text_lower for word in goodbye_words)
    
    def _end_call(self, session_id, user_input):
        """End call with quick, natural farewell"""
        
        # Use quick farewell for speed 
        farewell = "Thank you for calling. Have a great day!"
        
        # Customize farewell if we have order context
        if session_id in self.order_context and self.order_context[session_id]:
            farewell = "Glad I could help with your order. Have a great day!"
        
        response = VoiceResponse()
        response.say(farewell, voice='Polly.Joanna', language='en-US')
        response.hangup()
        
        print(f"[Twilio] Call ended naturally for session {session_id[:8]}...")
        
        # Close session
        session_manager.close_session(session_id)
        
        # Clean up context
        if session_id in self.conversation_context:
            del self.conversation_context[session_id]
        if session_id in self.order_context:
            del self.order_context[session_id]
        
        return str(response)
    
    def _error_response(self, message):
        """Return error response"""
        response = VoiceResponse()
        response.say(
            "I'm sorry, there was a technical issue. Please try calling again.",
            voice='Polly.Joanna',
            language='en-US'
        )
        response.hangup()
        return str(response)


# Initialize agent
print("[Twilio] Initializing LLM-Driven Twilio Voice Agent...")
agent = TwilioVoiceAgent()
print("[Twilio] Agent ready - All responses powered by Gemini AI")


# Flask routes
@app.route('/incoming_call', methods=['POST'])
def incoming_call():
    """Handle incoming call"""
    call_sid = request.values.get('CallSid')
    from_number = request.values.get('From')
    
    print(f"[Twilio] Incoming call from: {from_number}")
    print(f"[Twilio] Call SID: {call_sid}")
    
    response = agent.handle_incoming_call(call_sid)
    return Response(response, mimetype='text/xml')


@app.route('/process_speech', methods=['POST'])
def process_speech():
    """Process user's speech input"""
    call_sid = request.values.get('CallSid')
    speech_result = request.values.get('SpeechResult', '')
    
    print(f"[Twilio] User said: {speech_result}")
    
    response = agent.process_user_speech(call_sid, speech_result)
    return Response(response, mimetype='text/xml')


@app.route('/call_status', methods=['POST'])
def call_status():
    """Handle call status callbacks"""
    call_sid = request.values.get('CallSid')
    call_status = request.values.get('CallStatus')
    
    print(f"[Twilio] Call {call_sid} status: {call_status}")
    
    return Response('', mimetype='text/xml')


if __name__ == '__main__':
    print("\n" + "="*70)
    print("   TWILIO LLM-DRIVEN VOICE AGENT")
    print("   All responses generated by Gemini AI")
    print("="*70)
    print("\nStarting Flask server on http://0.0.0.0:5000")
    print("\nNext steps:")
    print("1. Start ngrok in another terminal: ngrok http 5000")
    print("2. Copy the ngrok HTTPS URL")
    print("3. Configure Twilio webhook: https://your-ngrok-url/incoming_call")
    print("4. Call your Twilio number!")
    print("\n" + "="*70 + "\n")
    
    app.run(host='0.0.0.0', port=5000, debug=True)